=== hussnainzafar/nzdpu/resources/json-schema/schema-form-create.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "schema-form-create.json",
  "title": "Schema - Create",
  "description": "Request body format for the 'Create Schema' API.",
  "type": "object",
  "properties": {
    "name": { "type":  "string" },
    "description": { "type": "string" },
    "user_id": { "type": "integer" },
    "view": {
      "type": "object",
      "properties": {
        "name": { "type": "string" },
        "description": { "type": "string" },
        "permissions_set_id": { "type":  "integer" },
        "constraint_view": { "type": "object" }
      },
      "required": ["name"]
    },
    "attributes": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": { "type": "string" },
          "user_id": { "type": "integer" },
          "type": {
            "enum": [
              "label","text", "bool", "int", "float", "datetime", "single","multiple", "form", "file", "form_or_null", "bool_or_null", "text_or_null", "float_or_null", "int_or_null", "file_or_null"
            ]
          },
          "type_id": { "type": "integer" },
          "view": {
            "type": "object",
            "properties": {
              "permissions_set_id": { "type":  "integer" },
              "constraint_value": {
                "type": "array",
                "items": {
                  "$ref": "schema-constraint.json"
                }
              },
              "constraint_view": { "type": "object" }
            }
          },
          "choices": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "choice_id": { "type":  "number" },
                "value": { "type": "string" },
                "description": { "type": "string" },
                "language_code": { "type": "string" }
              },
              "required": ["choice_id","value"]
            }
          },
          "prompts": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "value": { "type": "string" },
                "description": { "type": "string" },
                "language_code": { "type": "string" }
              },
              "required": ["value"]
            }
          },
          "form": {
            "$ref": "schema-form-create.json"
          }
        },
        "required": ["name","type"],
        "allOf": [
          {
            "if": {
              "properties": { "type": { "enum": ["single","multiple"] } }
            },
            "then": {
              "required": ["choices"]
            }
          },
          {
            "if": {
              "properties": { "type": { "const": ["form"] } }
            },
            "then": {
              "required": ["form"]
            }
          }
        ]
      }
    }
  },
  "required": ["name","user_id"]
}

=== hussnainzafar/nzdpu/tests/data/samples-for-client/schema-nzdpu-general-requirements.json
{
    "name": "nzdpu_general_requirements",
    "description": "NZDPU - General Requirements Form",
    "user_id": 1,
    "attributes": [
        {
            "name": "data_model",
            "type": "single",
            "prompts": [
                {
                    "value": "Reporting data model"
                }
            ],
            "choices": [
                {
                    "choice_id": 10001,
                    "choice_set_id": 1,
                    "value": "NZDPU Core"
                },
                {
                    "choice_id": 10002,
                    "choice_set_id": 1,
                    "value": "ISSB"
                },
                {
                    "choice_id": 10003,
                    "choice_set_id": 1,
                    "value": "EFRAG"
                }
            ],
            "view": {
                "constraint_value": [
                    {
                        "code": "required",
                        "actions": [
                            {
                                "set": {
                                    "required": true
                                }
                            }
                        ]
                    }
                ]
            }
        },
        {
            "name": "date_start_reporting_year",
            "type": "datetime",
            "prompts": [
                {
                    "value": "Reporting Period Start Date"
                }
            ],
            "view": {
                "constraint_value": [
                    {
                        "code": "reporting_period_range",
                        "actions": [
                            {
                                "set": {
                                    "required": true,
                                    "min": "2015-01-01T00:00:00.000Z",
                                    "max": "{currentDate}"
                                }
                            }
                        ]
                    }
                ]
            }
        },
        {
            "name": "date_end_reporting_year",
            "type": "datetime",
            "prompts": [
                {
                    "value": "Reporting Period End Date"
                }
            ],
            "view": {
                "constraint_value": [
                    {
                        "code": "reporting_period_range",
                        "actions": [
                            {
                                "set": {
                                    "required": true,
                                    "min": "2015-01-01T00:00:00.000Z",
                                    "max": "{currentDate}"
                                }
                            }
                        ]
                    }
                ]
            }
        },
        {
            "name": "org_boundary_approach",
            "type": "single",
            "choices": [
                {
                    "choice_id": 20001,
                    "choice_set_id": 2,
                    "value": "Operational control"
                },
                {
                    "choice_id": 20002,
                    "choice_set_id": 2,
                    "value": "Equity share"
                },
                {
                    "choice_id": 20003,
                    "choice_set_id": 2,
                    "value": "Financial control"
                },
                {
                    "choice_id": 20004,
                    "choice_set_id": 2,
                    "value": "Aligned with consolidated financial statement (and operational control for entities outside the consolidated accounting group)"
                },
                {
                    "choice_id": 20005,
                    "choice_set_id": 2,
                    "value": "Aligned with consolidated financial statement (and equity share for entities outside the consolidated accounting group)"
                }
            ],
            "prompts": [
                {
                    "value": "Organizational boundary approach used to consolidate GHG emissions"
                }
            ],
            "view": {
                "constraint_value": [
                    {
                        "code": "required",
                        "actions": [
                            {
                                "set": {
                                    "required": true
                                }
                            }
                        ]
                    }
                ]
            }
        }
    ]
}

=== hussnainzafar/nzdpu/tests/data/nzdpu-general-requirements.json
{
    "name": "nzdpu_general_requirements",
    "description": "NZDPU - General Requirements Form",
    "user_id": 1,
    "view": {
        "name": "nzdpu_general_requirements_view",
        "description": "NZDPU schema General Requirements view"
    },
    "attributes": [
        {
            "name": "general_features",
            "type": "label",
            "prompts": [
                {
                    "value": "General features",
                    "description": "General features",
                    "language_code": "en_US"
                }
            ],
            "view": {
                "constraint_view": {
                    "type": "label",
                    "item": {
                        "variant": "PRIMARY_HEADING"
                    }
                }
            }
        },
        {
            "name": "data_model",
            "type": "single",
            "prompts": [
                {
                    "value": "Reporting data model"
                }
            ],
            "choices": [
                {
                    "choice_id": 10001,
                    "value": "NZDPU Core",
                    "set_name": "data_model_list"
                },
                {
                    "choice_id": 10002,
                    "value": "ISSB",
                    "set_name": "data_model_list"
                },
                {
                    "choice_id": 10003,
                    "value": "EFRAG",
                    "set_name": "data_model_list"
                }
            ],
            "view": {
                "constraint_value": [
                    {
                        "code": "required",
                        "actions": [
                            {
                                "set": {
                                    "required": true
                                }
                            }
                        ]
                    }
                ],
                "constraint_view": {
                    "type": "single",
                    "layout": { "span": 6, "offset": 6 }
                }
            }
        },
        {
            "name": "date_start_reporting_year",
            "type": "datetime",
            "prompts": [
                {
                    "value": "Reporting Period Start Date"
                }
            ],
            "view": {
                "constraint_value": [
                    {
                        "code": "reporting_period_range",
                        "actions": [
                            {
                                "set": {
                                    "required": true,
                                    "min": "2015-01-01T00:00:00.000Z",
                                    "max": "{currentDate}"
                                }
                            }
                        ]
                    }
                ],
                "constraint_view": {
                    "type": "datetime",
                    "layout": { "span": 6 }
                }
            }
        },
        {
            "name": "date_end_reporting_year",
            "type": "datetime",
            "prompts": [
                {
                    "value": "Reporting Period End Date"
                }
            ],
            "view": {
                "constraint_value": [
                    {
                        "code": "reporting_period_range",
                        "actions": [
                            {
                                "set": {
                                    "required": true,
                                    "min": "2015-01-01T00:00:00.000Z",
                                    "max": "{currentDate}"
                                }
                            }
                        ]
                    }
                ],
                "constraint_view": {
                    "type": "datetime",
                    "layout": { "span": 6 }
                }
            }
        },
        {
            "name": "org_boundary_approach",
            "type": "single",
            "choices": [
                {
                    "choice_id": 20001,
                    "value": "Operational control",
                    "set_name": "org_boundary_approach_list"
                },
                {
                    "choice_id": 20002,
                    "value": "Equity share",
                    "set_name": "org_boundary_approach_list"
                },
                {
                    "choice_id": 20003,
                    "value": "Financial control",
                    "set_name": "org_boundary_approach_list"
                },
                {
                    "choice_id": 20004,
                    "value": "Aligned with consolidated financial statement (and operational control for entities outside the consolidated accounting group)",
                    "set_name": "org_boundary_approach_list"
                },
                {
                    "choice_id": 20005,
                    "value": "Aligned with consolidated financial statement (and equity share for entities outside the consolidated accounting group)",
                    "set_name": "org_boundary_approach_list"
                }
            ],
            "prompts": [
                {
                    "value": "Organizational boundary approach used to consolidate GHG emissions"
                }
            ],
            "view": {
                "constraint_value": [
                    {
                        "code": "required",
                        "actions": [
                            {
                                "set": {
                                    "required": true
                                }
                            }
                        ]
                    }
                ],
                "constraint_view": {
                    "type": "single",
                    "layout": { "span": 6 }
                }
            }
        }
    ]
}

=== hussnainzafar/nzdpu/tests/data/form-create.json
{
  "name": "nzdpu_form",
  "description": "NZDPU SCHEMA 4.0",
  "user_id": 1,
  "view": {
    "name": "nzdpu_form_simple_test",
    "description": "A sample questionnaire view"
  },
  "attributes": [
    {
      "name": "disclosure_source",
      "type": "text",
      "prompts": [
        {
          "value": "Disclosure source"
        }
      ]
    },
    {
      "name": "legal_entity_identifier",
      "type": "text_or_null",
      "prompts": [
        {
          "value": "legal_entity_identifier"
        }
      ]
    },
    {
      "name": "data_model",
      "type": "text",
      "prompts": [
        {
          "value": "Data model for disclosure"
        }
      ],
      "view": {
        "constraint_value": [
          {
            "code": "data_model_min",
            "actions": [
              {
                "set": {
                  "min": 5
                }
              }
            ]
          }
        ]
      }
    },
    {
      "name": "date_start_reporting_year",
      "type": "datetime",
      "prompts": [
        {
          "value": "Reporting period start date"
        }
      ]
    },
    {
      "name": "date_end_reporting_year",
      "type": "datetime",
      "prompts": [
        {
          "value": "Reporting period end date"
        }
      ],
      "view": {
        "constraint_value": [
          {
            "code": "current_date_range",
            "actions": [
              {
                "set": {
                  "required": true,
                  "min": "2023-06-27T00:00:00.000Z",
                  "max": "{currentDate}"
                }
              }
            ]
          }
        ]
      }
    },
    {
      "name": "reporting_year",
      "type": "int",
      "prompts": [
        {
          "value": "Reporting year"
        }
      ],
      "view": {
        "constraint_view": {
          "type": "int",
          "nzdpuForm": "GENERAL_DISCLOSURE",
          "view": [
            "DATA_EXPLORER"
          ],
          "item": {
            "variant": "YEAR"
          }
        },
        "constraint_value": [
          {
            "code": "reporting_year_range",
            "actions": [
              {
                "set": {
                  "min": 2015,
                  "max": 2022
                }
              }
            ]
          }
        ]
      }
    },
    {
      "name": "org_boundary_approach",
      "type": "text_or_null",
      "prompts": [
        {
          "value": "Organizational boundary approach used to consolidate GHG emissions"
        }
      ]
    },
    {
      "name": "reporting_datetime",
      "type": "datetime",
      "prompts": [
        {
          "value": "Reporting date"
        }
      ]
    },
    {
      "name": "scope_1_emissions_group",
      "type": "text",
      "prompts": [
        {
          "value": "Scope 1 Emissions"
        }
      ]
    }
  ]
}
